export const HomeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-1.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
}
export const HomeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Unlimited Access',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
  buttonLabel: 'Learn More',
  imgStart: true,
  img: require('../../images/svg-3.svg'),
  alt: 'Piggybank',
  dark: false,
  primary: false,
  darkText: true,
}
export const HomeObjThree = {
  id: 'signup',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Services',
  headline: 'Know our Services',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
  buttonLabel: 'Start Now',
  imgStart: false,
  img: require('../../images/svg-2.svg'),
  alt: 'Pig',
  dark: true,
  primary: true,
  darkText: false,
}
export const HomeObjFour = {
  id: 'services',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'All our services',
  headline: 'The best way to improve your skills',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
  buttonLabel: 'Learn More',
  imgStart: true,
  img: require('../../images/svg-4.svg'),
  alt: 'Piggybank',
  dark: false,
  primary: false,
  darkText: true,
}
